### PR TITLE
Adds a new `list` reporter

### PR DESCRIPTION
**Pull request by luislobo**
Adds a new `list` reporter, with a more streamlined output.
Lets you do `| grep critical` (for example), as it prints everything in one line.

Please check the TODO comment to see if it's valid

I also have a change for `npm` that I'm about to send after this one, so that `npm audit` has a `--list` parameter 

Adresses #7

### CODE REVIEW

**Comment by evilpacket** [comment]
@luislobo I haven't had a chance to test this out, do you happen to have a screenshot of the output (I swear I've seen one someplace and thought it was here but now it's not so I'm confused) :)

**Comment by luislobo** [comment]
@zkat suggested changing it as `--parseable` making it output the result like `npm install --parseable`, I think that both use cases are valid, the `--list` one and the `--parseable` one. If you agree, I can add also `parseable`

`npm install --parseable` outputs something like this:

```
add	abbrev	1.1.1	node_modules/fsevents/node_modules/abbrev		
add	ansi-regex	2.1.1	node_modules/fsevents/node_modules/ansi-regex		
add	aproba	1.2.0	node_modules/fsevents/node_modules/aproba		
add	balanced-match	1.0.0	node_modules/fsevents/node_modules/balanced-match		
add	chownr	1.0.1	node_modules/fsevents/node_modules/chownr		
add	code-point-at	1.1.0	node_modules/fsevents/node_modules/code-point-at		
add	concat-map	0.0.1	node_modules/fsevents/node_modules/concat-map		
add	brace-expansion	1.1.11	node_modules/fsevents/node_modules/brace-expansion		
add	console-control-strings	1.1.0	node_modules/fsevents/node_modules/console-control-strings		
add	core-util-is	1.0.2	node_modules/fsevents/node_modules/core-util-is		
```

**Comment by zkat** [comment]
oh. I guess this happened because of renaming the default branch to `latest`.

**Comment by zkat** [comment]
fixed :)

**Comment by luislobo** [comment]
Awesome :heart_eyes:

**Comment by zkat** [comment]
I'm gonna /cc @iarna and @evilpacket on this to get their perspective on the `--list` view. I'm neutral on it and would still like a `--parseable` reporter (and I still think `--list` could be replaced with a fairly readable version of `--parseable`).

**Comment by luislobo** [comment]
I could make a `--parseable` version with colors, as I've seen that colors can be configured too. We could add a param for --no-color (didn't check yet how disabling the colors work works internally)
I'm fine with getting rid of the "table".
One question though, it's a funcional one. Can you check the PR, there is a TODO/TOCHECK here: https://github.com/npm/npm-audit-report/pull/10/files#diff-a06ff6c66ce9794c6a36389e432a5266R117

**Comment by iarna** [comment]
npm cli side, parseable output should never have colors (it is solely intended for consumption by tooling and should not require additional flags).

**Comment by luislobo** [comment]
Replaced this PR with https://github.com/npm/npm-audit-report/pull/21, closing this one.

New one has `--parseable`, has no colors, passes lint and enhanced tests.

**Pull request closed without merging**
